[project]
name = 'Decentralized-Energy-Grid-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumer-identity]
path = 'contracts/consumer-identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.producer-verification]
path = 'contracts/producer-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
